apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Address of Prometheus container
    isDefault: true
    basicAuth: false
    jsonData:
      timeInterval: "5s"
