global:
  scrape_interval: 15s # Default scrape interval for all targets
  evaluation_interval: 15s # Default rule evaluation interval

scrape_configs:
  # Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

    # Monitor Grafana itself
  - job_name: "grafana"
    static_configs:
      - targets: ["localhost:3001"] # Metrics endpoint
    basic_auth:
      username: metrics # Basic auth username (if configured)
      password: metrics # Basic auth password (if configured)

  # # Monitor Kafka Exporter
  # - job_name: "kafka-exporter"
  #   static_configs:
  #     - targets: ["kafka-exporter:9308"]

  # # Monitor ZooKeeper Exporter
  # - job_name: "zookeeper-exporter"
  #   static_configs:
  #     - targets: ["zookeeper-exporter:9141"]

  # # Monitor MongoDB Exporters
  # - job_name: "mongodb-exporter-config"
  #   static_configs:
  #     - targets: ["mongo-exporter-config:9216"]
  # - job_name: "mongodb-exporter-shard1"
  #   static_configs:
  #     - targets: ["mongo-exporter-shard1:9217"]
  # - job_name: "mongodb-exporter-shard2"
  #   static_configs:
  #     - targets: ["mongo-exporter-shard2:9218"]
  # - job_name: "mongodb-exporter-shard3"
  #   static_configs:
  #     - targets: ["mongo-exporter-shard3:9219"]
