version: '3'

services:
  # Config Server (MongoDB Sharded Cluster)
  mongo-config1:
    image: mongo:latest
    container_name: mongo-config1
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27019:27019"
    volumes:
      - mongo-config1-data:/data/db
    networks:
      - mongo-net

  # MongoDB Exporter for Config Server
  mongo-exporter-config:
    image: bitnami/mongodb-exporter:latest
    container_name: mongo-exporter-config
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongo-config1:27019
    ports:
      - "9216:9216"  # Prometheus will scrape metrics from this port
    networks:
      - mongo-net
    restart: unless-stopped

  # Shard 1 (Replica Set)
  mongo-shard1-1:
    image: mongo:latest
    container_name: mongo-shard1-1
    command: ["mongod", "--shardsvr", "--replSet", "shardReplSet1", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27022:27017"
    volumes:
      - mongo-shard1-1-data:/data/db
    networks:
      - mongo-net

  mongo-shard1-2:
    image: mongo:latest
    container_name: mongo-shard1-2
    command: ["mongod", "--shardsvr", "--replSet", "shardReplSet1", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27023:27017"
    volumes:
      - mongo-shard1-2-data:/data/db
    networks:
      - mongo-net

  # MongoDB Exporter for Shard 1
  mongo-exporter-shard1:
    image: bitnami/mongodb-exporter:latest
    container_name: mongo-exporter-shard1
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongo-shard1-1:27017
    ports:
      - "9217:9216"  # Prometheus will scrape metrics from this port
    networks:
      - mongo-net
    restart: unless-stopped

  # Shard 2 (Replica Set)
  mongo-shard2-1:
    image: mongo:latest
    container_name: mongo-shard2-1
    command: ["mongod", "--shardsvr", "--replSet", "shardReplSet2", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27024:27017"
    volumes:
      - mongo-shard2-1-data:/data/db
    networks:
      - mongo-net

  mongo-shard2-2:
    image: mongo:latest
    container_name: mongo-shard2-2
    command: ["mongod", "--shardsvr", "--replSet", "shardReplSet2", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27025:27017"
    volumes:
      - mongo-shard2-2-data:/data/db
    networks:
      - mongo-net

  # MongoDB Exporter for Shard 2
  mongo-exporter-shard2:
    image: bitnami/mongodb-exporter:latest
    container_name: mongo-exporter-shard2
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongo-shard2-1:27017
    ports:
      - "9218:9216"  # Prometheus will scrape metrics from this port
    networks:
      - mongo-net
    restart: unless-stopped

  # Shard 3 (Replica Set)
  mongo-shard3-1:
    image: mongo:latest
    container_name: mongo-shard3-1
    command: ["mongod", "--shardsvr", "--replSet", "shardReplSet3", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27026:27017"
    volumes:
      - mongo-shard3-1-data:/data/db
    networks:
      - mongo-net

  mongo-shard3-2:
    image: mongo:latest
    container_name: mongo-shard3-2
    command: ["mongod", "--shardsvr", "--replSet", "shardReplSet3", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27027:27017"
    volumes:
      - mongo-shard3-2-data:/data/db
    networks:
      - mongo-net

  # MongoDB Exporter for Shard 3
  mongo-exporter-shard3:
    image: bitnami/mongodb-exporter:latest
    container_name: mongo-exporter-shard3
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongo-shard3-1:27017
    ports:
      - "9219:9216"  # Prometheus will scrape metrics from this port
    networks:
      - mongo-net
    restart: unless-stopped

  # Mongos Router
  mongos-router:
    image: mongo:latest
    container_name: mongos-router
    command: ["mongos", "--configdb", "configReplSet/mongo-config1:27019", "--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge

volumes:
  mongo-config1-data:
  mongo-shard1-1-data:
  mongo-shard1-2-data:
  mongo-shard2-1-data:
  mongo-shard2-2-data:
  mongo-shard3-1-data:
  mongo-shard3-2-data:
