services:
  # First Shard Cluster
  mongoshard11:
    build:
      context: replicaset
    container_name: mongoshard11
    depends_on:
      - mongoshard12
      - mongoshard13
    command: mongod --shardsvr --replSet shard1 --dbpath /data/db --port 27017
    environment:
      - REPLICA_SET=shard1
    expose:
      - "27017"
    volumes:
      - shard_d11:/data/db

  mongoshard12:
    image: mongo
    container_name: mongoshard12
    command: mongod --shardsvr --replSet shard1 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_d12:/data/db

  mongoshard13:
    image: mongo
    container_name: mongoshard13
    command: mongod --shardsvr --replSet shard1 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_d13:/data/db

  # Second Shard Cluster
  mongoshard21:
    build:
      context: replicaset
    container_name: mongoshard21
    depends_on:
      - mongoshard22
      - mongoshard23
    command: mongod --shardsvr --replSet shard2 --dbpath /data/db --port 27017
    environment:
      - REPLICA_SET=shard2
    expose:
      - "27017"
    volumes:
      - shard_d21:/data/db

  mongoshard22:
    image: mongo
    container_name: mongoshard22
    command: mongod --shardsvr --replSet shard2 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_d22:/data/db

  mongoshard23:
    image: mongo
    container_name: mongoshard23
    command: mongod --shardsvr --replSet shard2 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_d23:/data/db

  # Config Cluster
  mongocfg1:
    build:
      context: replicaset
    container_name: mongocfg1
    depends_on:
      - mongocfg2
      - mongocfg3
    command: mongod --configsvr --replSet cfg --dbpath /data/db --port 27017
    environment:
      - REPLICA_SET=cfg
    expose:
      - "27017"
    volumes:
      - shard_c1:/data/db

  mongocfg2:
    image: mongo
    container_name: mongocfg2
    command: mongod --configsvr --replSet cfg --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_c2:/data/db

  mongocfg3:
    image: mongo
    container_name: mongocfg3
    command: mongod --configsvr --replSet cfg --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - shard_c3:/data/db

  # Build mongos Router
  mongos1:
    build:
      context: build/router
    container_name: mongos1
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
      - mongoshard11
      - mongoshard12
      - mongoshard13
      - mongoshard21
      - mongoshard22
      - mongoshard23
    command: mongos --configdb cfg/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
    environment: #we can specify only the primary node for each cluster shard, other nodes will appear automatically
      - SHARDS=shard1/mongoshard11;shard2/mongoshard21
    ports:
      - 27027:27017
    expose:
      - "27017"

  # MongoDB Exporters for Monitoring
  mongoexporter_shard1:
    image: bitnami/mongodb-exporter:latest
    container_name: mongoexporter_shard1
    depends_on:
      - mongoshard11
    environment:
      - MONGODB_URI=mongodb://mongoshard11:27017
    ports:
      - "9216:9216"

  mongoexporter_shard12:
    image: bitnami/mongodb-exporter:latest
    container_name: mongoexporter_shard12
    depends_on:
      - mongoshard12
    environment:
      - MONGODB_URI=mongodb://mongoshard12:27017
    ports:
      - "9220:9216"

  mongoexporter_shard13:
    image: bitnami/mongodb-exporter:latest
    container_name: mongoexporter_shard13
    depends_on:
      - mongoshard13
    environment:
      - MONGODB_URI=mongodb://mongoshard13:27017
    ports:
      - "9221:9216"

  mongoexporter_shard2:
    image: bitnami/mongodb-exporter:latest
    container_name: mongoexporter_shard2
    depends_on:
      - mongoshard21
    environment:
      - MONGODB_URI=mongodb://mongoshard21:27017
    ports:
      - "9217:9216"

  mongoexporter_shard22:
    image: bitnami/mongodb-exporter:latest
    container_name: mongoexporter_shard22
    depends_on:
      - mongoshard22
    environment:
      - MONGODB_URI=mongodb://mongoshard22:27017
    ports:
      - "9222:9216"

  mongoexporter_shard23:
    image: bitnami/mongodb-exporter:latest
    container_name: mongoexporter_shard23
    depends_on:
      - mongoshard23
    environment:
      - MONGODB_URI=mongodb://mongoshard23:27017
    ports:
      - "9223:9216"

  mongoexporter_cfg:
    image: bitnami/mongodb-exporter:latest
    container_name: mongoexporter_cfg
    depends_on:
      - mongocfg1
    environment:
      - MONGODB_URI=mongodb://mongocfg1:27017
    ports:
      - "9218:9216"

  mongoexporter_mongos:
    image: bitnami/mongodb-exporter:latest
    container_name: mongoexporter_mongos
    depends_on:
      - mongos1
    environment:
      - MONGODB_URI=mongodb://mongos1:27017
    ports:
      - "9219:9216"

volumes:
  shard_d11:
  shard_d12:
  shard_d13:
  shard_d21:
  shard_d22:
  shard_d23:
  shard_c1:
  shard_c2:
  shard_c3:
