services:
  # Zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # Allow unauthenticated users to connect
    ports:
      - "2181:2181" # Zookeeper client port
    networks:
      - swarmdb-network
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    deploy:
      placement:
        constraints:
          - node.hostname == zookeeper-node # Ensure this service runs on the zookeeper-node
      restart_policy:
        condition: on-failure # Restart only on failure

  # Zookeeper Exporter
  zookeeper-exporter:
    image: dabealu/zookeeper-exporter:latest
    container_name: zookeeper-exporter
    environment:
      - ZOOKEEPER_SERVERS=zookeeper:2181 # Address of the Zookeeper server
      - ZOOKEEPER_EXPORTER_LOG_LEVEL=info
    ports:
      - "9141:9141" # Port for Prometheus to scrape metrics
    depends_on:
      - zookeeper
    networks:
      - swarmdb-network
    deploy:
      placement:
        constraints:
          - node.hostname == zookeeper-node # Ensure this service runs on the zookeeper-node
      restart_policy:
        condition: on-failure # Restart only on failure

  # Kafka
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 # Connect Kafka to Zookeeper
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-node:9092 # Advertise Kafka on kafka-node
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes # Allow plaintext connections
    ports:
      - "9092:9092" # Kafka broker port
    depends_on:
      - zookeeper
    networks:
      - swarmdb-network
    volumes:
      - kafka_data:/bitnami/kafka
    deploy:
      placement:
        constraints:
          - node.hostname == kafka-node # Ensure this service runs on the kafka-node
      restart_policy:
        condition: on-failure # Restart only on failure

  # Kafka Exporter
  kafka-exporter:
    image: bitnami/kafka-exporter:latest
    container_name: kafka-exporter
    environment:
      - KAFKA_BROKER_SERVER=kafka:9092 # Address of the Kafka broker
      - KAFKA_EXPORTER_LOG_LEVEL=info
    ports:
      - "9308:9308" # Port for Prometheus to scrape metrics
    depends_on:
      - kafka
    networks:
      - swarmdb-network
    deploy:
      placement:
        constraints:
          - node.hostname == kafka-node # Ensure this service runs on the kafka-node
      restart_policy:
        condition: on-failure # Restart only on failure

networks:
  swarmdb-network:
    driver: overlay # Using an overlay network to connect across multiple nodes in Docker Swarm

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
