services:
  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Custom Prometheus config
      - prometheus-data:/prometheus
    ports:
      - "9090:9090" # Prometheus web UI and /metrics endpoint
    networks:
      - monitoring
    restart: always

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=dds_admin
      - GF_SECURITY_ADMIN_PASSWORD=dds_bois
      - GF_METRICS_ENABLED=true # Enable the /metrics endpoint
    ports:
      - "3000:3000" # Grafana web UI
      - "3001:3001" # Grafana /metrics endpoint
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
