services:
  configsvr:
    image: mongo
    container_name: configsvr
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--bind_ip_all"]
    ports:
      - "27019:27019"
    volumes:
      - configsvr:/data/db

  shard1:
    image: mongo
    container_name: shard1
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--bind_ip_all"]
    ports:
      - "27018:27018"
    volumes:
      - shard1:/data/db

  shard2:
    image: mongo
    container_name: shard2
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--bind_ip_all"]
    ports:
      - "27020:27020"
    volumes:
      - shard2:/data/db

  shard3:
    image: mongo
    container_name: shard3
    command: ["mongod", "--shardsvr", "--replSet", "shard3ReplSet", "--bind_ip_all"]
    ports:
      - "27021:27021"
    volumes:
      - shard3:/data/db

  mongos:
    image: mongo
    container_name: mongos
    command: ["mongos", "--configdb", "configReplSet/configsvr:27019", "--bind_ip_all"]
    ports:
      - "27017:27017"
    depends_on:
      - configsvr
      - shard1
      - shard2
      - shard3

volumes:
  configsvr:
  shard1:
  shard2:
  shard3: